/**
 * GCCL Interactive Lab Tour — Content Data
 * -----------------------------------------------------------------------
 * SOURCE OF TRUTH: this file is a direct transcription of lab_data.xlsx.
 * To change any lab name, description, video link, or brochure link,
 * edit the values below — nothing else in the site needs to change.
 *
 * Excel column reference:
 *   키워드 (keyword)   -> id
 *   시설명 (facility)  -> name
 *   소개 (intro)        -> description
 *   영상 링크 (video)   -> video (relative path to mp4 file)
 *   관련 홍보물 (docs)  -> materials[]
 * -----------------------------------------------------------------------
 */

const GCCL_DATA = {
  // Landing / Company Overview panel content (Excel row: "open")
  overview: {
    id: "open",
    name: "Company Overview",
    description:
      "GCCL provides end-to-end clinical trial sample analysis services, supporting drug development from Phase I through Phase IV.",
    video: "videos/open.mp4",
    materials: [
      { label: "Brochure", url: "https://drive.google.com/file/d/18LfRnxHxAdxYO6tS2NrYkgsLDETjxcFO/view?usp=sharing" },
      { label: "Lab Map", url: "https://drive.google.com/file/d/1vi66X3To5hXw1CapIXbG2tBeZGIVfc_d/view?usp=sharing" }
    ]
  },

  // The 6 interactive hotspots on the lab map.
  // coords are [x,y] percentage pairs relative to the map image (0-100),
  // converted from the original GCCL.html pixel coordinates (1920x1080 canvas).
  labs: [
    {
      id: "sm",
      name: "Sample Management",
      shortLabel: "Sample Mgmt",
      description:
        "The 24-hour operating analysis lab preprocess and stores samples collected from subjects in a customized format. GCCL utilizes barcodes generated by our IT system to receive and manage samples, oversees the entire process, and operates a dedicated laboratory for sample preparation.",
      video: "videos/sm.mp4",
      materials: [
        { label: "PBMC Isolation", url: "https://drive.google.com/file/d/1NES4SQOc7SYcCzp8BguA0_J9V0WEEJ8O/view?usp=sharing" }
      ],
      shape: "poly",
      coords: [
        [27.45, 75.37], [50.52, 57.31], [54.58, 64.81], [50.52, 68.33],
        [55.68, 77.04], [35.94, 94.35]
      ]
    },
    {
      id: "lk",
      name: "Project Management & Lab Kit Production",
      shortLabel: "Lab Kit / PM",
      description:
        "Each project is supported by a dedicated Project Manager and managed through G-HUB, GCCL's proprietary client portal and project management platform. GCCL also offers customized lab kit design and management, ensuring efficient sample collection and accurate analysis at every study visit.",
      video: "videos/lk.mp4",
      materials: [
        { label: "G-HUB", url: "https://drive.google.com/file/d/1cFX9ZaZsHqmwq8SicO2DrwMsPCMIHrF9/view?usp=sharing" }
      ],
      shape: "poly",
      coords: [
        [43.28, 17.87], [57.24, 39.44], [69.53, 30.19], [56.35, 9.72]
      ]
    },
    {
      id: "bal",
      name: "Bioanalytical Lab",
      shortLabel: "Bioanalytical Lab",
      description:
        "Bio Analytical Lab specializes in analyzing PK/PD, ADA, biomarkers, etc., in early clinical trials and provides LBA(Ligand Binding Assay), CBA(Cell Based Assay), qPCR, LC-MS/MS, and Flow Cytometry services. In addition, GCCL is the first in Korea to introduce a global Laboratory Information Management System(LIMS) to ensure more accurate data to meet global standards.",
      video: "videos/bal.mp4",
      materials: [
        { label: "Bioanalytical Lab Services", url: "https://drive.google.com/file/d/1f0tCJoDkhm16KtYDI-s-5LKvjJRtPM2A/view?usp=sharing" }
      ],
      shape: "poly",
      coords: [
        [50.73, 53.52], [60.89, 71.57], [85.94, 50.09], [74.48, 35.0]
      ]
    },
    {
      id: "bl3",
      name: "Bio-Safety Level 3",
      shortLabel: "BL3 Lab",
      description:
        "Within biosafety facilities spanning over 300m2 (certified for Biosafety Level 3- BL2, BL3), GCCL offers various research and verification services for drug candidates, including neutralizing antibody analysis using live viruses based on infectious disease viruses.",
      video: "videos/bl3.mp4",
      materials: [
        { label: "Vaccine Trial Experience", url: "https://drive.google.com/file/d/15dS0790tqOunBFNrsmnyyxkFfbgva_QX/view?usp=sharing" }
      ],
      shape: "poly",
      coords: [
        [14.01, 41.02], [30.78, 29.17], [42.03, 51.67], [24.95, 64.54]
      ]
    },
    {
      id: "cl",
      name: "Central Lab",
      shortLabel: "Clinical Lab",
      description:
        "GCCL provides reliable data through systematic management and automated analysis of safety and efficacy tests.",
      video: "videos/cl.mp4",
      materials: [
        { label: "Central Lab Services", url: "https://drive.google.com/file/d/1SRRKn5yuBhFHvuM1eM51ga4RTKAiaMmr/view?usp=sharing" }
      ],
      shape: "poly",
      coords: [
        [30.57, 25.28], [40.99, 18.7], [54.79, 41.11], [44.06, 49.44]
      ]
    }
  ],

  // Contact CTA (Excel row: "문의")
  contact: {
    heading: "Contact GCCL",
    description:
      "Interested in GCCL's clinical trial sample analysis services? Submit your inquiry below, and our team will respond promptly with the right solution for your project.",
    ctaLabel: "Submit an Inquiry",
    ctaUrl: "https://eng.gccl.co.kr/board/board_online/board_form01.asp?scrID=0000000278&pageNum=6&subNum=1&ssubNum=1"
  },

  // Footer / company links (Excel row: "기타")
  links: [
    { label: "Website", url: "https://eng.gccl.co.kr/" },
    { label: "LinkedIn", url: "https://www.linkedin.com/company/global-clinical-central-lab" },
    { label: "YouTube", url: "https://www.youtube.com/@GlobalClinicalCentralLab" },
    { label: "KakaoTalk", url: "https://pf.kakao.com/_mxkhxlG" },
    { label: "Naver Blog", url: "https://blog.naver.com/gclcstudy" }
  ]
};
